# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{riotjs-xpcc}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["alexyoung", "gabrielg"]
  s.date = %q{2009-10-24}
  s.description = %q{JS version of the Riot testing framework}
  s.email = %q{info@conflagrationjs.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".gitmodules",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/riotjs.rb",
     "riotjs-xpcc.gemspec",
     "xpcomcore/doc/files.html",
     "xpcomcore/doc/index.html",
     "xpcomcore/doc/symbols/_global_.html",
     "xpcomcore/doc/symbols/src/xpcomcore_lib_riot.js.html",
     "xpcomcore/lib/riot.js"
  ]
  s.homepage = %q{http://www.conflagrationjs.org/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{JS version of the Riot testing framework}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xpcomcore-rubygem>, [">= 0"])
      s.add_development_dependency(%q<jsdoc-toolkit>, [">= 0"])
    else
      s.add_dependency(%q<xpcomcore-rubygem>, [">= 0"])
      s.add_dependency(%q<jsdoc-toolkit>, [">= 0"])
    end
  else
    s.add_dependency(%q<xpcomcore-rubygem>, [">= 0"])
    s.add_dependency(%q<jsdoc-toolkit>, [">= 0"])
  end
end

